### ISSUE TITLE
全て在庫無しとなった場合、ユーザに何かしらの通知をする。

### ISSUE THREAD

**Issue by Ok-Yuki** [seita1224/stock_info_transfer#4]
## タスク
出品停止の自動化ができるまでの暫定対応として、
在庫なしとなった場合に、何かしらの方法でユーザーに通知を行う。

（ユーザーが出品停止した場合に、csvの商品と出品先の情報が
一致しているかをチェックする際にエラーとなってしまう？？）

### 作業
1.対応用のブランチを作成
2.通知方法の検討
3.実装

**Comment by seita1224** [comment]
ブランチをdeveloperに切り出してコミットしている

**Comment by seita1224** [comment]
動作確認済みのためクローズする
